### ISSUE TITLE
Preferences don't work 

### ISSUE THREAD

**Issue by dicson** [baverman/snaked#8]
test@dicson:~/Desktop/snaked$ snaked -s test '/home/test/.local/share/gajim/plugins/clients_icons/clients_icons.py' 
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.3.5-py2.6.egg/snaked/core/shortcuts.py", line 95, in activate
    result = cb(*args)
  File "/usr/local/lib/python2.6/dist-packages/snaked-0.3.5-py2.6.egg/snaked/core/gui/prefs.py", line 44, in activate
    name = model.get_value(iter, 0)
TypeError: iter must be a GtkTreeIter

**Comment by baverman** [comment]
Fixed. Now message will be popuped.

The root of the problem: you press Enter without selecting needed preferences item.

Thanks for report.

**Comment by dicson** [comment]
Not fixed:
python run-snaked.py -s test '/home/test/.local/share/gajim/plugins/clients_icons/clients_icons.py' 
Traceback (most recent call last):
  File "/home/test/Desktop/snaked/snaked/core/shortcuts.py", line 95, in activate
    result = cb(*args)
  File "/home/test/Desktop/snaked/snaked/core/gui/prefs.py", line 46, in activate
    name = model.get_value(iter, 0)
TypeError: iter must be a GtkTreeIter

diff --git a/snaked/core/gui/prefs.py b/snaked/core/gui/prefs.py
index 2b3428f..72c9d28 100644
--- a/snaked/core/gui/prefs.py
+++ b/snaked/core/gui/prefs.py
     def activate(self):
         (model, iter) = self.dialogs_view.get_selection().get_selected()
         if not iter:
             self.editor().message('You need select item')
-            return
       name = model.get_value(iter, 0)
       prefs.registered_dialogs[name][1](self.editor%28%29)
       idle(self.hide)

**Comment by baverman** [comment]
My fault, sorry. Now it is fixed.

**Comment by baverman** [comment]
closed
